from enum import Enum


class CredentialsType(str, Enum):
    API_KEY = "API_KEY"
    OAUTH1 = "OAUTH1"
    OAUTH2 = "OAUTH2"
    OAUTH2_NOSECRET = "OAUTH2_NOSECRET"
    OAUTH2_SIGNATURE = "OAUTH2_SIGNATURE"
    OPEN_BANKING_AUTO = "OPEN_BANKING_AUTO"
    OPEN_BANKING_AUTO_EMAIL = "OPEN_BANKING_AUTO_EMAIL"
    OPEN_BANKING_IBM = "OPEN_BANKING_IBM"
    OPEN_BANKING_MANUAL = "OPEN_BANKING_MANUAL"
    OPEN_BANKING_NO_KEY = "OPEN_BANKING_NO_KEY"
    OPEN_BANKING_NO_TRANSPORT = "OPEN_BANKING_NO_TRANSPORT"
    OPEN_BANKING_UK_AUTO = "OPEN_BANKING_UK_AUTO"
    OPEN_BANKING_UK_MANUAL = "OPEN_BANKING_UK_MANUAL"
    OPEN_BANKING_WITH_TPP_ID_AND_SECRET = "OPEN_BANKING_WITH_TPP_ID_AND_SECRET"
    TOKEN_IO = "TOKEN_IO"

    def __str__(self) -> str:
        return str(self.value)
