from enum import Enum


class AccountBalanceType(str, Enum):
    AUTHORISED = "AUTHORISED"
    CLOSING_AVAILABLE = "CLOSING_AVAILABLE"
    CLOSING_BOOKED = "CLOSING_BOOKED"
    CLOSING_CLEARED = "CLOSING_CLEARED"
    EXPECTED = "EXPECTED"
    FORWARD_AVAILABLE = "FORWARD_AVAILABLE"
    INFORMATION = "INFORMATION"
    INTERIM_AVAILABLE = "INTERIM_AVAILABLE"
    INTERIM_BOOKED = "INTERIM_BOOKED"
    INTERIM_CLEARED = "INTERIM_CLEARED"
    OPENING_AVAILABLE = "OPENING_AVAILABLE"
    OPENING_BOOKED = "OPENING_BOOKED"
    OPENING_CLEARED = "OPENING_CLEARED"
    OTHER = "OTHER"
    PREVIOUSLY_CLOSED_BOOKED = "PREVIOUSLY_CLOSED_BOOKED"
    UNKNOWN = "UNKNOWN"

    def __str__(self) -> str:
        return str(self.value)
