from enum import Enum


class AccountType(str, Enum):
    CASH_INCOME = "CASH_INCOME"
    CASH_PAYMENT = "CASH_PAYMENT"
    CASH_TRADING = "CASH_TRADING"
    CHARGES = "CHARGES"
    CHARGE_CARD = "CHARGE_CARD"
    COMMISSION = "COMMISSION"
    CREDIT_CARD = "CREDIT_CARD"
    CURRENT = "CURRENT"
    E_MONEY = "E_MONEY"
    LIMITED_LIQUIDITY_SAVINGS_ACCOUNT = "LIMITED_LIQUIDITY_SAVINGS_ACCOUNT"
    LOAN = "LOAN"
    MARGINAL_LENDING = "MARGINAL_LENDING"
    MONEY_MARKET = "MONEY_MARKET"
    MORTGAGE = "MORTGAGE"
    NON_RESIDENT_EXTERNAL = "NON_RESIDENT_EXTERNAL"
    OTHER = "OTHER"
    OVERDRAFT = "OVERDRAFT"
    OVERNIGHT_DEPOSIT = "OVERNIGHT_DEPOSIT"
    PREPAID_CARD = "PREPAID_CARD"
    SALARY = "SALARY"
    SAVINGS = "SAVINGS"
    SETTLEMENT = "SETTLEMENT"
    TAX = "TAX"
    UNKNOWN = "UNKNOWN"

    def __str__(self) -> str:
        return str(self.value)
