from enum import Enum


class AuthorisationStatus(str, Enum):
    AUTHORIZED = "AUTHORIZED"
    AWAITING_AUTHORIZATION = "AWAITING_AUTHORIZATION"
    AWAITING_DECOUPLED_AUTHORIZATION = "AWAITING_DECOUPLED_AUTHORIZATION"
    AWAITING_DECOUPLED_PRE_AUTHORIZATION = "AWAITING_DECOUPLED_PRE_AUTHORIZATION"
    AWAITING_FURTHER_AUTHORIZATION = "AWAITING_FURTHER_AUTHORIZATION"
    AWAITING_PRE_AUTHORIZATION = "AWAITING_PRE_AUTHORIZATION"
    AWAITING_RE_AUTHORIZATION = "AWAITING_RE_AUTHORIZATION"
    AWAITING_SCA_CODE = "AWAITING_SCA_CODE"
    AWAITING_SCA_METHOD = "AWAITING_SCA_METHOD"
    CONSUMED = "CONSUMED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    INVALID = "INVALID"
    PRE_AUTHORIZED = "PRE_AUTHORIZED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"
    UNKNOWN = "UNKNOWN"

    def __str__(self) -> str:
        return str(self.value)
