import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, Union

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.categorisation import Categorisation
    from ..models.enrichment_merchant import EnrichmentMerchant
    from ..models.transaction_hash import TransactionHash


T = TypeVar("T", bound="Enrichment")


@_attrs_define
class Enrichment:
    """Enriched data that has been derived by Yapily using it's data processing and machine learning techniques.

    Attributes:
        categorisation (Union[Unset, Categorisation]): Income and Expense categorisation that the Yapily categorisation
            engine has determined for the transaction.
        transaction_hash (Union[Unset, TransactionHash]): An unique identifier for the transaction that was generated by
            Yapily. This is a hash of transaction attributes and may be useful an id is not present (and therefore hasn't
            been provided by an Institution).
        cleansed_description (Union[Unset, str]): Cleaned version of the `Transaction Description` that removes
            miscellaneous, generic and unhelpful text.
        merchant (Union[Unset, EnrichmentMerchant]): Details of the merchant, identified by Yapily data services.
        location (Union[Unset, str]): The location of where the transaction took place.
        payment_processor (Union[Unset, str]): A payment provider that manages (credit/debit) transactions between the
            `Institution` and the merchant.
        corrected_date (Union[Unset, datetime.datetime]): The likely date and time on which the transaction took place.
            This is distinct from `Booking Date Time` which usually refers to the post-clearing value.
    """

    categorisation: Union[Unset, "Categorisation"] = UNSET
    transaction_hash: Union[Unset, "TransactionHash"] = UNSET
    cleansed_description: Union[Unset, str] = UNSET
    merchant: Union[Unset, "EnrichmentMerchant"] = UNSET
    location: Union[Unset, str] = UNSET
    payment_processor: Union[Unset, str] = UNSET
    corrected_date: Union[Unset, datetime.datetime] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        categorisation: Union[Unset, dict[str, Any]] = UNSET
        if not isinstance(self.categorisation, Unset):
            categorisation = self.categorisation.to_dict()

        transaction_hash: Union[Unset, dict[str, Any]] = UNSET
        if not isinstance(self.transaction_hash, Unset):
            transaction_hash = self.transaction_hash.to_dict()

        cleansed_description = self.cleansed_description

        merchant: Union[Unset, dict[str, Any]] = UNSET
        if not isinstance(self.merchant, Unset):
            merchant = self.merchant.to_dict()

        location = self.location

        payment_processor = self.payment_processor

        corrected_date: Union[Unset, str] = UNSET
        if not isinstance(self.corrected_date, Unset):
            corrected_date = self.corrected_date.isoformat()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if categorisation is not UNSET:
            field_dict["categorisation"] = categorisation
        if transaction_hash is not UNSET:
            field_dict["transactionHash"] = transaction_hash
        if cleansed_description is not UNSET:
            field_dict["cleansedDescription"] = cleansed_description
        if merchant is not UNSET:
            field_dict["merchant"] = merchant
        if location is not UNSET:
            field_dict["location"] = location
        if payment_processor is not UNSET:
            field_dict["paymentProcessor"] = payment_processor
        if corrected_date is not UNSET:
            field_dict["correctedDate"] = corrected_date

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.categorisation import Categorisation
        from ..models.enrichment_merchant import EnrichmentMerchant
        from ..models.transaction_hash import TransactionHash

        d = dict(src_dict)
        _categorisation = d.pop("categorisation", UNSET)
        categorisation: Union[Unset, Categorisation]
        if isinstance(_categorisation, Unset):
            categorisation = UNSET
        else:
            categorisation = Categorisation.from_dict(_categorisation)

        _transaction_hash = d.pop("transactionHash", UNSET)
        transaction_hash: Union[Unset, TransactionHash]
        if isinstance(_transaction_hash, Unset):
            transaction_hash = UNSET
        else:
            transaction_hash = TransactionHash.from_dict(_transaction_hash)

        cleansed_description = d.pop("cleansedDescription", UNSET)

        _merchant = d.pop("merchant", UNSET)
        merchant: Union[Unset, EnrichmentMerchant]
        if isinstance(_merchant, Unset):
            merchant = UNSET
        else:
            merchant = EnrichmentMerchant.from_dict(_merchant)

        location = d.pop("location", UNSET)

        payment_processor = d.pop("paymentProcessor", UNSET)

        _corrected_date = d.pop("correctedDate", UNSET)
        corrected_date: Union[Unset, datetime.datetime]
        if isinstance(_corrected_date, Unset):
            corrected_date = UNSET
        else:
            corrected_date = isoparse(_corrected_date)

        enrichment = cls(
            categorisation=categorisation,
            transaction_hash=transaction_hash,
            cleansed_description=cleansed_description,
            merchant=merchant,
            location=location,
            payment_processor=payment_processor,
            corrected_date=corrected_date,
        )

        enrichment.additional_properties = d
        return enrichment

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
